spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      properties:
        spring.json.add.type.headers: ${SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS}

  minio:
    url: ${SPRING_MINIO_URL}
    access-key: ${SPRING_MINIO_ACCESS_KEY}
    secret-key: ${SPRING_MINIO_SECRET_KEY}
    bucket: ${SPRING_MINIO_BUCKET}
    region: ${SPRING_MINIO_REGION}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate.format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

springdoc:
  api-docs:
    path: ${SPRINGDOC_API_DOCS_PATH}

  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
    operationsSorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONSSORTER}
    tagsSorter: ${SPRINGDOC_SWAGGER_UI_TAGSSORTER}

  show-actuator: ${SPRINGDOC_SHOW_ACTUATOR}