spring:
  application:
    name: async-document-processor

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      properties:
        spring.json.add.type.headers: ${SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_HEADERS}

  minio:
    url: ${SPRING_MINIO_URL}
    access-key: ${SPRING_MINIO_ACCESS_KEY}
    secret-key: ${SPRING_MINIO_SECRET_KEY}
    bucket: ${SPRING_MINIO_BUCKET}
    region: ${SPRING_MINIO_REGION}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: ProcessorPdfPool
      register-mbeans: true
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

  show-actuator: true